# Generated by Django 5.2.6 on 2025-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='About')),
                ('place_type', models.CharField(choices=[('Synagogue', 'Guliver'), ('KMC', 'Mohyla-Academy'), ('Bilyi Naliv', 'Poshtova'), ('Troeschuna', 'ny ce baza'), ('ATB', 'Kyiv')], max_length=20, verbose_name='Type of place')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of create')),
            ],
        ),
    ]
